baseURL = "https://mytrashcan.netlify.app/"
languageCode = "en-us"
title = "TrashCan"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowPostNavLinks = true
  description = "'cause i've got thoughts on everything."
  comments = true
  googleSiteVerify = "XYephQBaAe6NTf-e15AbZmrnRNf47Udd8JNerJh0i8Q"

  [params.homeInfoParams]
    Title = "TrashCan"
    Content = "'cause i've got thoughts on everything."
